#!/usr/bin/env python3

from src.args import parse_args
from src.trigo import main


def entrypoint() -> int:
    args = parse_args()

    main(args)
    return 0


if __name__ == "__main__":
    exit(entrypoint())
